name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore UseItApp.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore UseItApp.sln
      
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" UseItApp.Tests
      
    - name: Upload backend test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-test-results
        path: UseItApp.Tests/TestResults/**/*.xml
        
    - name: Upload backend coverage report
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage-report
        path: UseItApp.Tests/TestResults/**/coverage.cobertura.xml

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './UseItApp.API/ClientApp/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./UseItApp.API/ClientApp
    
    - name: Lint
      run: npx ng lint
      working-directory: ./UseItApp.API/ClientApp
      
    - name: Build
      run: npx ng build --configuration production
      working-directory: ./UseItApp.API/ClientApp
    
    - name: Test
      run: npx ng test --browsers=ChromeHeadless --watch=false --code-coverage
      working-directory: ./UseItApp.API/ClientApp
      
    - name: Upload frontend coverage report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage-report
        path: ./UseItApp.API/ClientApp/coverage/
